### ISSUE TITLE
Implement support for autocompletion in location fields using Google Places data

### ISSUE THREAD

**Issue by GoncaloPascoal** [FEUP-ESOF-2020-21/open-cx-t6g4-the-five-engineers#18]
### Summary
Using a package like [Flutter Google Places](https://pub.dev/packages/flutter_google_places), we can suggest locations from Google's database as the user types.

### To-Do
- [x] Install required dependencies
- [ ] Add location field to create a conference screen
- [ ] Integrate autocompletion

**Comment by biam05** [comment]
Google Places autocompletion requires payment for API requests, therefore we are dropping this feature.
